name: Third workflow
on:
  workflow_run:
    workflows: [second workflow]
    types:
      - completed
jobs:
  Hello-command:
    runs-on: ubuntu-latest
    steps:
      - name: List files and copy repo
        run: echo "Hello Third workflow"